stages:
  - test
  - build

# Этап 1: Тестирование Go кода
test:
  stage: test
  image: golang:1.17
  script:
    - echo "Starting Go tests..."
    - go test -v .
    - echo "Tests completed successfully!"
  artifacts:
    reports:
      junit: report.xml
    expire_in: 1 week
  only:
    - branches

# Этап 2: Сборка Docker образа
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building Docker image..."
    - docker build -t sdvps-app:latest .
    - echo "Build completed!"
  only:
    - main
    - master
